# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ucr_integration_voice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ucr_integration_voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bucr_integration_voice.proto\x12\x0bintegration\"\xbb\x01\n\x12IntegrationMessage\x12\x34\n\x0bvoice_begin\x18\x01 \x01(\x0b\x32\x1d.integration.RemoteVoiceBeginH\x00\x12\x32\n\nvoice_data\x18\x02 \x01(\x0b\x32\x1c.integration.RemoteVoiceDataH\x00\x12\x30\n\tvoice_end\x18\x03 \x01(\x0b\x32\x1b.integration.RemoteVoiceEndH\x00\x42\t\n\x07message\"\x97\x01\n\x12\x41udioConfiguration\x12\x10\n\x08\x63hannels\x18\x01 \x01(\r\x12\x13\n\x0bsample_rate\x18\x02 \x01(\r\x12\x30\n\rsample_format\x18\x03 \x01(\x0e\x32\x19.integration.SampleFormat\x12(\n\x06\x66ormat\x18\x04 \x01(\x0e\x32\x18.integration.AudioFormat\"^\n\x10RemoteVoiceBegin\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x36\n\rconfiguration\x18\x02 \x01(\x0b\x32\x1f.integration.AudioConfiguration\"6\n\x0fRemoteVoiceData\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x0f\n\x07samples\x18\x02 \x01(\x0c\"$\n\x0eRemoteVoiceEnd\x12\x12\n\nsession_id\x18\x01 \x01(\r*f\n\x0cSampleFormat\x12\x19\n\x15SAMPLE_FORMAT_UNKNOWN\x10\x00\x12\x06\n\x02I8\x10\x01\x12\x07\n\x03I16\x10\x02\x12\x07\n\x03I32\x10\x03\x12\x06\n\x02U8\x10\x04\x12\x07\n\x03U16\x10\x05\x12\x07\n\x03U32\x10\x06\x12\x07\n\x03\x46\x33\x32\x10\x07*0\n\x0b\x41udioFormat\x12\x18\n\x14\x41UDIO_FORMAT_UNKNOWN\x10\x00\x12\x07\n\x03PCM\x10\x01\x42 \n\x1e\x63om.unfoldedcircle.integrationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ucr_integration_voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.unfoldedcircle.integration'
  _globals['_SAMPLEFORMAT']._serialized_start=578
  _globals['_SAMPLEFORMAT']._serialized_end=680
  _globals['_AUDIOFORMAT']._serialized_start=682
  _globals['_AUDIOFORMAT']._serialized_end=730
  _globals['_INTEGRATIONMESSAGE']._serialized_start=45
  _globals['_INTEGRATIONMESSAGE']._serialized_end=232
  _globals['_AUDIOCONFIGURATION']._serialized_start=235
  _globals['_AUDIOCONFIGURATION']._serialized_end=386
  _globals['_REMOTEVOICEBEGIN']._serialized_start=388
  _globals['_REMOTEVOICEBEGIN']._serialized_end=482
  _globals['_REMOTEVOICEDATA']._serialized_start=484
  _globals['_REMOTEVOICEDATA']._serialized_end=538
  _globals['_REMOTEVOICEEND']._serialized_start=540
  _globals['_REMOTEVOICEEND']._serialized_end=576
# @@protoc_insertion_point(module_scope)
