name: Publish ucapi on PyPI

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-24.04

    name: Verify Python build context
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f test-requirements.txt ]; then pip install -r test-requirements.txt; fi
      - name: Analyzing the code with pylint
        run: |
          python -m pylint ucapi
      - name: Lint with flake8
        run: |
          python -m flake8 ucapi --count --show-source --statistics
      - name: Check code formatting with isort
        run: |
          python -m isort ucapi/. examples/. --check --verbose
      - name: Check code formatting with black
        run: |
          python -m black ucapi examples --check --verbose

  build:
    name: Build and publish PyPi package
    needs: verify
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'unfoldedcircle'
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build setuptools setuptools_scm
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
